version: '3.9'

services:
  my-neo4j:
    image: neo4j:latest
    container_name: my-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/abc@123!zxy
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data:
